/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Control.ClientesControl;
import Modelo.Clientes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author marcelo adrian
 */
public class Cliente extends javax.swing.JFrame {
    
TableRowSorter<DefaultTableModel> sorter;
    private static final long serialVersionUID = 1L;

ClientesControl clientesControl =new ClientesControl();
Clientes clientesObj = null;
ArrayList clientesList = new ArrayList();
    /**
     * Creates new form Cliente
     */
    public Cliente() {
      
        initComponents();
    this.setLocationRelativeTo(null);
    this.refresh(1);
    }
     private void refresh(int par) {
     
     DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("idcli");
        modelo.addColumn("cedula");
        modelo.addColumn("nom"); 
        modelo.addColumn("tel");
       
        

        clientesList = clientesControl.listar("");
        Object[] fila = new Object[4];
    Integer n = clientesObj.getIdcli();
    
     for (int i = 0; i < clientesList.size(); i++) {
            fila[0] = clientesObj.getIdcli();
            fila[1] = clientesObj.getCedula();
            fila[2] = clientesObj.getNom();
            fila[3] = clientesObj.getTel();
            modelo.addRow(fila);
            
            clientesObj = (Clientes) clientesList.get(i);
        } 
     
        tblClientes.setModel(modelo);
           tblClientes.setAutoCreateRowSorter(true);
           sorter= new TableRowSorter<>(modelo);
           tblClientes.setRowSorter(sorter);
              
        lblidCli.setText("");
        txtCi.setText("");
        txtNombres.setText("");
        txtTelefono.setText("");
        btnCargar.setText("Cargar Datos Del Cliente");
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtCi = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btn_ficha = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblidCli = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Completo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cedula de Identidad");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        txtNombres.setBackground(new java.awt.Color(51, 51, 51));
        txtNombres.setForeground(new java.awt.Color(204, 204, 204));
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 410, -1));

        txtCi.setBackground(new java.awt.Color(51, 51, 51));
        txtCi.setForeground(new java.awt.Color(204, 204, 204));
        txtCi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiActionPerformed(evt);
            }
        });
        getContentPane().add(txtCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 210, -1));

        txtTelefono.setBackground(new java.awt.Color(51, 51, 51));
        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 250, -1));

        btnCargar.setBackground(new java.awt.Color(51, 51, 51));
        btnCargar.setForeground(new java.awt.Color(204, 204, 204));
        btnCargar.setText("Cargar Datos Del Cliente");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        tblClientes.setAutoCreateRowSorter(true);
        tblClientes.setBackground(new java.awt.Color(51, 51, 51));
        tblClientes.setForeground(new java.awt.Color(204, 204, 204));
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Cedula De Identidad", "Nombre Completo", "Telefono"
            }
        ));
        tblClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblClientes.setGridColor(new java.awt.Color(204, 204, 204));
        tblClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        tblClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(0).setHeaderValue("Id");
            tblClientes.getColumnModel().getColumn(1).setHeaderValue("Cedula De Identidad");
            tblClientes.getColumnModel().getColumn(2).setHeaderValue("Nombre Completo");
            tblClientes.getColumnModel().getColumn(3).setHeaderValue("Telefono");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 241, 1300, 310));

        btnBorrar.setBackground(new java.awt.Color(51, 51, 51));
        btnBorrar.setForeground(new java.awt.Color(204, 204, 204));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 150, -1));

        btn_ficha.setText("Ficha Tecnica del Vehiculo");
        btn_ficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fichaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ficha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 10, 230, -1));

        txtBuscar.setBackground(new java.awt.Color(51, 51, 51));
        txtBuscar.setForeground(new java.awt.Color(204, 204, 204));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 200, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo principal 2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1300, 613));

        lblidCli.setText("Iid");
        lblidCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblidCliActionPerformed(evt);
            }
        });
        getContentPane().add(lblidCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 30, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("deprecation")
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    
                Login pl = new  Login();

                pl.setVisible(true);

                hide();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtCiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
      
        Integer idcli = null;
        String idcliStr = lblidCli.getText();
        String cedulaStr = txtCi.getText();
        String nom = txtNombres.getText();
        String tel = txtTelefono.getText();
      
        Integer cedula = null;
        String mensaje = null;

        try {

            if (!idcliStr.equals("")) {
                idcli = Integer.parseInt(idcliStr);
            }

            cedula = Integer.parseInt(cedulaStr);

            clientesObj = new Clientes(idcli, cedula, nom, tel);

            if (clientesObj.getIdcli() == null) {
                clientesControl.insertar(clientesObj);
                mensaje = "Insertado";
            } else {
                clientesControl.modificar(clientesObj);
                mensaje = "Modificado";
            }
            this.refresh(1);
            JOptionPane.showMessageDialog(null, mensaje+" con exito.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                "El documento de identidad deber ser valor numerico");
        }
        
    }//GEN-LAST:event_btnCargarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void lblidCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblidCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblidCliActionPerformed
   
    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        Integer filaNum = tblClientes.getSelectedRow();
        if( filaNum<0 ){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        } else {
            DefaultTableModel Modelo = (DefaultTableModel) tblClientes.getModel();
            Integer idCli = (Integer) Modelo.getValueAt(filaNum, 0);
             clientesObj = new Clientes();
             clientesObj.setIdCli(idCli);
             clientesControl.eliminar( clientesObj );
        this.refresh(1);
            JOptionPane.showMessageDialog(null, "Eliminado con exito!");
        }
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btn_fichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fichaActionPerformed
        // TODO add your handling code here:
         //  Integer idcli=null;
            // String idcliStr = lblidCli.getText();
             /* String Nom = txtNombres.getText();
            if (!idcliStr.equals("")) */
               // idcli = Integer.parseInt(idcliStr);
                 JOptionPane.showMessageDialog(null,"Accediendo a Ficha Tecnica Del Vehiculo \t");
                   frmFicha pl = new  frmFicha();

                pl.setVisible(true);

                hide();
          /*  }
            else{
                  JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
            }*/
            
           /*if (filaNum < 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro");
        } else {
               filaNum= filaNum +1;
               JOptionPane.showMessageDialog(null,"Ficha tecnica del Vehiculo del Cliente de la fila :\t"+ filaNum);

                Ficha pl = new  Ficha();

                pl.setVisible(true);

                hide();
  
           }*/
    }//GEN-LAST:event_btn_fichaActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased

         try{
      
            sorter.setRowFilter(RowFilter.regexFilter(txtBuscar.getText() ));
            
              tblClientes.setRowSorter(sorter);
        }
            
  catch(Exception e){
  }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
           try{
      
            sorter.setRowFilter(RowFilter.regexFilter(txtBuscar.getText( )));  
              tblClientes.setRowSorter(sorter);
        }
            
  catch(Exception e){

      
  }
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void tblClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblClientesKeyPressed
        // TODO add your handling code here:
         int seleccion= tblClientes.getSelectedRow();
     
    clientesObj = (Clientes) clientesList.get(seleccion);
            lblidCli.setText(clientesObj.getIdcli().toString());
            txtCi.setText(clientesObj.getCedula().toString());
            txtNombres.setText(clientesObj.getNom()); 
            txtTelefono.setText(clientesObj.getTel());
            
            btnCargar.setText("Actualizar datos del Cliente");
            
    }//GEN-LAST:event_tblClientesKeyPressed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
     int seleccion= tblClientes.getSelectedRow();
    clientesObj = (Clientes) clientesList.get(seleccion);
            lblidCli.setText(clientesObj.getIdcli().toString());
            txtCi.setText(clientesObj.getCedula().toString());
            txtNombres.setText(clientesObj.getNom()); 
            txtTelefono.setText(clientesObj.getTel());
            
          
             
                 btnCargar.setText("Actualizar datos del Cliente");
            
             
        // TODO add your handling code here:
    }//GEN-LAST:event_tblClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btn_ficha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField lblidCli;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCi;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
